import type { NextPage } from 'next'
import Head from 'next/head'
import ChatUi from '../components/chatUi'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chat-Ui</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChatUi />
    </div>
  )
}

export default Home
